#!/usr/bin/env bash

# $1 should be the username
# $2 is the command line or command of the process to check
is_user_running_process()
{
    ps -u "$1" -o cmd | grep -q "^$2$" || ps -u "$1" -o comm | grep -q "^$2$"
}

for u in $(users | tr ' ' '\n' | sort -u); do
    screensaver_running=false

    if is_user_running_process "$u" xlock; then
        screensaver_running=true
    else
        for p in $(ls /usr/libexec/xscreensaver); do
            if is_user_running_process "$u" "$p -root"; then
                screensaver_running=true
                break
            fi
        done
    fi

    echo $u $screensaver_running
done
